#!/usr/bin/env python2

import sys
from PyQt4 import QtCore, QtGui
from GUI_ import *
from tools_ import *
from os import geteuid

#Makes the log
logger.makeLog()

#Check if user is root
if geteuid() == 0:
    logger.writeLog('rootWarning')


#Start turbulence
if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == "ozoneBlack":
            ui = MainGui_ozoneBlack.Ui_MainWindow()
        elif sys.argv[1] == "manjaroGrey":
            ui = MainGui_manjaroGrey.Ui_MainWindow()
        else:
            ui = MainGui_manjaroGrey.Ui_MainWindow()
    else:
        ui = MainGui_manjaroGrey.Ui_MainWindow()
  
    logger.writeLog('logHeader')
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    #ui = MainGui.Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    qr = MainWindow.frameGeometry()
    cp = QtGui.QDesktopWidget().availableGeometry().center()
    qr.moveCenter(cp)
    MainWindow.move(qr.topLeft())
    
    MainWindow.show()
    app.exec_()
    logger.writeLog('exitTurbulence')

