#!/usr/bin/env python2

import sys
from PyQt4 import QtCore, QtGui
from GUI_ import *
from tools_ import *
from os import geteuid, environ, path
from locale import getdefaultlocale

#Makes the log
logger.makeLog()

#Check if user is root
if geteuid() == 0:
    logger.writeLog('rootWarning')


#Start turbulence
if __name__ == "__main__":
    ui = MainGui_manjaroGrey.Ui_MainWindow()
  
    logger.writeLog('logHeader')
    app = QtGui.QApplication(sys.argv)
    
    locale = getdefaultlocale()
    
    if path.isfile('/usr/share/turbulence/tr/qt_%s.qm' % locale[0]): 
        try: 
            with open('/usr/share/turbulence/tr/qt_%s.qm' % locale[0]):
                trFile = '/usr/share/turbulence/tr/qt_%s.qm' % locale[0]
        except IOError:
            print 'File IO error on %s' % locale[0]
    elif path.isfile('/usr/share/turbulence/tr/qt_%s.qm' % locale[0].split("_")[0]):
        try: 
            with open('/usr/share/turbulence/tr/qt_%s.qm' % locale[0].split("_")[0]):
                trFile = '/usr/share/turbulence/tr/qt_%s.qm' % locale[0].split("_")[0]
        except IOError:
            print 'File IO error on %s' % locale[0].split("_")[0]
    else:
        trFile = '/usr/share/turbulence/tr/qt_en.qm'
        
    translator = QtCore.QTranslator(app)
    translator.load(trFile)
    app.installTranslator(translator)
    
    #To set force the use of a locale, uncomment the code below, and comment the code above.
    #translator = QtCore.QTranslator(app)
    #translator.load('/usr/share/turbulence/tr/qt_zh_CN.qm')
    #app.installTranslator(translator)
    
    MainWindow = QtGui.QMainWindow()
    #ui = MainGui.Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    qr = MainWindow.frameGeometry()
    cp = QtGui.QDesktopWidget().availableGeometry().center()
    qr.moveCenter(cp)
    MainWindow.move(qr.topLeft())
    
    MainWindow.show()
    app.exec_()
    logger.writeLog('exitTurbulence')

